### ISSUE TITLE
rem2pi

### ISSUE THREAD

**Issue by togo59** [JuliaPhysics/Measurements.jl#27]
Is there a way around this (in Julia 1.0.2):
`using Measurements`
`julia> rem2pi(7pi/(4 ± 0.2), RoundDown)`
`ERROR: MethodError: no method matching rem2pi(::Measurement{Float64}, ::RoundingMode{:Down})`

The reason I encountered this as I am trying to use Rotations.jl with uncertainty provided by Measurements.jl

Could extend the function Base.rem2pi() for special types I suppose.

**Comment by giordano** [comment]
Thank you so much for the report!  There was already a method for `mod2pi` but not for `rem2pi`.

> Is there a way around this (in Julia 1.0.2):

Actually yes!  Right now, without waiting for #29 to be merged,  you can use the `@uncertain` macro which computes numerically the derivatives:

```julia
julia> @uncertain (x -> rem2pi(x, RoundDown))(7pi/(4 ± 0.2))
5.497787143782138 ± 0.2748893571875781
```

Note that this is a bit tricky because the `@uncertain` macro works on a function call whose arguments are all `Measurement` objects or objects that can be converted to `Measurement`, but you can work around this limitation by using anonymous functions, see https://juliaphysics.github.io/Measurements.jl/stable/examples.html#@uncertain-Macro-1

After #29 you'll get

```julia
julia> rem2pi(7pi/(4 ± 0.2), RoundDown)
5.497787143782138 ± 0.2748893571891069
```

so `@uncertain` is already pretty accurate
